name: docs

on:
  push:
    branches: [ main, docs ]

  workflow_dispatch:

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './src/'

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: generate markdown and concatenate
        run: |
          python -m pydoc -w src/*
          ls
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: './web/'

      - name: promote
        run: |
          cd web
          mkdir index
          cd ../
          pwd
          cp -rp ./*.html web/index
          cd web/index
          ls
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'publish generated docs'
          add: 'index'
          cwd: './web/'
          author_name: 'Relay Pro builder'
          author_email: 'info@relaypro.com'
          push: true
