name: docs

on:
  push:
    branches: [ fix-404 ]

  workflow_dispatch:

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './src/'

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: generate markdown and concatenate
        run: |
          cd src/relay
          sudo apt install python3-pip
          pip3 install websockets
          pip3 install requests
          python generate_docs.py
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: './web/'

      - name: promote
        run: |
          cd web
          cp -rpv ../src/relay/*.html .
          cp -pv ../src/relay/workflow.html index.html
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'publish generated docs'
          cwd: './web/'
          add: '.'
          author_name: 'Relay Pro builder'
          author_email: 'info@relaypro.com'
          push: true
