name: docs

on:
  push:
    branches: [ main, docs ]

  workflow_dispatch:

jobs:
  build:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './src/'

      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: generate markdown and concatenate
        run: |
          cd src
          python
          quit()
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          path: './web/'

      - name: promote
        run: |
          cd web
          cp ../src/API.md ./index.md
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'publish generated docs'
          add: '*.md'
          cwd: './web/'
          author_name: 'Relay Pro builder'
          author_email: 'info@relaypro.com'
          push: true
